---
- name: 2/7 install - 1 - Ensure openwrt_dir exists
  file:
    path: "{{ openwrt_dir }}"
    state: directory

- name: 2/7 install - 3 - Clone openwrt
  git:
    repo: "{{ openwrt_repository }}"
    dest: "{{ openwrt_buildroot_dir }}"
    single_branch: yes
    version: "{{ openwrt_version_tag }}"
    update: no

- name: 2/7 install - 4 - cp feeds.conf.default feeds.conf
  ansible.builtin.copy:
    src: "{{ openwrt_buildroot_dir }}/feeds.conf.default"
    dest: "{{ openwrt_buildroot_dir }}/feeds.conf"
    force: no
    remote_src: true
  notify: "Update and install feeds"
