---
- name: build - Clean Openwrt target images
  shell: make target/linux/clean
  args:
    chdir: "{{ openwrt_build_dir }}"
  when: not skip_build_openwrt_target_clean
  tags:
    - build_openwrt_target_clean

- name: build - Build OpenWrt
  shell: make -j $(nproc) EXTRA_IMAGE_NAME="{{openwrt_extra_image_name}}"
  args:
    chdir: "{{ openwrt_build_dir }}"
  when: not skip_build_openwrt
  tags:
    - build_openwrt